create table worker (id int8 generated by default as identity, daily_income float8 not null, name varchar(250) not null, primary key (id));
create table worker (id int8 generated by default as identity, daily_income float8 not null, name varchar(250) not null, primary key (id));
