INSERT INTO WORKER (NAME, DAILY_INCOME) VALUES ('Bob Green', 200.0);
INSERT INTO WORKER (NAME, DAILY_INCOME) VALUES ('Maria Brown', 300.0);
INSERT INTO WORKER (NAME, DAILY_INCOME) VALUES ('Alex Grey', 250.0);